### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by seppo0010** [auth0/limitd#56]
```
npm http 404 https://registry.npmjs.org/auth0-instrumentation
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.8.11
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "."
npm ERR! cwd /home/seppo/Projects/limitd
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
npm ERR! Error: No compatible version found: protobufjs@'github:jfromaniello/protobuf.js#v5.1.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.0","0.9.1","0.9.3","0.9.4","0.9.5","0.9.6","0.9.7","0.9.8","0.9.9","0.9.10","0.9.11","0.9.12","0.9.13","0.10.0","0.11.0","0.11.1","0.11.2","0.12.0","0.12.1","0.12.2","0.12.3","0.12.4","0.12.5","0.12.6","0.12.7","0.12.8","0.12.9","0.12.10","0.12.11","0.12.12","0.12.13","1.0.0-b1","1.0.0-b2","1.0.0-b4","1.0.0-b5","1.0.0-b6","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.1.0","1.1.1","1.1.2","1.1.3","1.1.4","1.1.6","1.1.7","1.1.8","1.1.9","1.3.0","1.3.1","1.3.2","1.5.0","1.5.1","2.0.0-rc1","2.0.0-rc2","2.0.0-rc4","2.0.0","2.0.1","2.0.2","2.0.3","2.0.4","2.0.5","2.2.1","3.0.0","3.2.0","3.2.1","3.2.2","3.2.4","3.3.0","3.3.1","3.4.0","3.4.1","3.5.1","3.5.2","3.5.4","3.5.5","3.6.0","3.7.0","3.8.0","3.8.1","3.8.2","4.0.0-b2","4.0.0-b3","4.0.0-b4","4.0.0-b5","4.0.0","4.1.0","4.1.1","4.1.2","5.0.0","4.1.3","5.0.1"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.8.11
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "."
npm ERR! cwd /home/seppo/Projects/limitd
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/seppo/Projects/limitd/npm-debug.log
npm ERR! not ok code 0
```

**Comment by seppo0010** [comment]
I'm gonna guess my nodejs version is too old, darn ubuntu
